### ISSUE TITLE
Does not work on PHP 5.4.14...

### ISSUE THREAD

**Issue by HallofFamer** [zenovich/runkit#47]
Get this error in the process, what should I do?

running: make
/bin/sh /root/tmp/pear/pear-build-root0i4zWf/runkit-1.0.3/libtool --mode=compile cc -I. -I/root/tmp/pear/runkit -DPHP_ATOM_INC -I/root/tmp/pear/pear-build-root0i4zWf/runkit-1.0.3/include -I/root/tmp/pear/pear-build-root0i4zWf/runkit-1.0.3/main -I/root/tmp/pear/runkit -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/tmp/pear/runkit/runkit.c -o runkit.lo
mkdir .libs
cc -I. -I/root/tmp/pear/runkit -DPHP_ATOM_INC -I/root/tmp/pear/pear-build-root0i4zWf/runkit-1.0.3/include -I/root/tmp/pear/pear-build-root0i4zWf/runkit-1.0.3/main -I/root/tmp/pear/runkit -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/tmp/pear/runkit/runkit.c -fPIC -DPIC -o .libs/runkit.o
/root/tmp/pear/runkit/runkit.c: In function ‘php_runkit_register_auto_global’:
/root/tmp/pear/runkit/runkit.c:285: warning: passing argument 3 of ‘zend_register_auto_global’ makes integer from pointer without a cast
/root/tmp/pear/runkit/runkit.c:285: error: too few arguments to function ‘zend_register_auto_global’
/root/tmp/pear/runkit/runkit.c: In function ‘zm_deactivate_runkit’:
/root/tmp/pear/runkit/runkit.c:378: warning: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type
/root/tmp/pear/runkit/runkit.c:388: warning: passing argument 2 of ‘zend_hash_apply’ from incompatible pointer type
/root/tmp/pear/runkit/runkit.c:396: warning: passing argument 2 of ‘zend_hash_apply_with_arguments’ from incompatible pointer type
make: **\* [runkit.lo] Error 1
ERROR: `make' failed
